### ISSUE TITLE
Issue with the latest version of UV which support the CUNI helpers (not the official version)

### ISSUE THREAD

**Issue by anisaR** [UnifiedViews/Core#319]
After updating to the latest version of UV (from develop repo), together with the helpers from Plugin-DevEnv (from develop repo as well) it is possible to compile a DPU created with the cuni helpers but it is not possible to upload it in UV since it returns an error as shown in the attachment.

Can you please give us any advice how to fix this issue.

![schermata_del_2015-03-09_17_37_59](https://cloud.githubusercontent.com/assets/4330270/6572595/a5ca1230-c713-11e4-9544-a904bc858d90.png)

**Comment by skodape** [comment]
This was not cause by merge, but by following commits in develop branch.

**Comment by jakubklimek** [comment]
I can confirm I am also blocked by this issue:
![image](https://cloud.githubusercontent.com/assets/718827/6573630/178ddf56-c71d-11e4-8c6e-9bcddbd06275.png)

**Comment by tomas-knap** [comment]
Caused by commit https://github.com/UnifiedViews/Plugin-DevEnv/commit/a80d72cfa9af959cda6ea62acd61ded3956ed123

Should be reverted asap by the author

**Comment by eea01** [comment]
Repaired in [this line](https://github.com/UnifiedViews/Core/commit/d986ae8c64268207021cf926eb5f49c9ab5e6d34#diff-dd5636ea2eed792a7fdd42d789420a8eR3).

**Comment by AndreAga** [comment]
Thanks a lot.

**Comment by jakubklimek** [comment]
The supposed fix further broken Core build for me:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[15,38] error: package org.apache.commons.codec.binary does not exist
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[43,25] error: cannot find symbol
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[71,65] error: cannot find symbol
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ODCleanStore ....................................... SUCCESS [  1.920 s]
[INFO] dataunit ........................................... SUCCESS [  6.315 s]
[INFO] dataunit-file ...................................... SUCCESS [  0.080 s]
[INFO] dataunit-file-impl ................................. SUCCESS [  3.364 s]
[INFO] dataunit-rdf ....................................... SUCCESS [  3.727 s]
[INFO] dataunit-rdf-impl .................................. SUCCESS [  4.690 s]
[INFO] dataunit-relational-impl ........................... SUCCESS [  4.870 s]
[INFO] commons-app ........................................ FAILURE [  3.161 s]
[INFO] frontend ........................................... SKIPPED
[INFO] backend ............................................ SKIPPED
[INFO] lib ................................................ SKIPPED
[INFO] lib-core ........................................... SKIPPED
[INFO] module-test ........................................ SKIPPED
[INFO] master ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.420 s
[INFO] Finished at: 2015-03-10T14:04:57+01:00
[INFO] Final Memory: 85M/525M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project commons-app: Compilation failure: Compilation failure:
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[15,38] error: package org.apache.commons.codec.binary does not exist
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[43,25] error: cannot find symbol
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[71,65] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :commons-app
```

**Comment by tomas-knap** [comment]
Bojan, you are creating more and more issues. Please solve this issue by reverting these two commits: 

- https://github.com/UnifiedViews/Core/commit/d986ae8c64268207021cf926eb5f49c9ab5e6d34
- https://github.com/UnifiedViews/Plugin-DevEnv/commit/a80d72cfa9af959cda6ea62acd61ded3956ed123

And create feature branches feature/Cryptography e.g. where we can discuss - discussion is anyway needed!

**Comment by eea01** [comment]
Reverted [cryptography](https://github.com/UnifiedViews/Core/commit/d882f7e94de1f6532269ef8fea1ea2478a9f419a).

**Comment by tomas-knap** [comment]
Please revert also: https://github.com/UnifiedViews/Plugin-DevEnv/commit/a80d72cfa9af959cda6ea62acd61ded3956ed123

**Comment by tomas-knap** [comment]
Than please assign on Anisa, so that she can test that.

**Comment by jakubklimek** [comment]
The original issue still stands, build now passes again

**Comment by tomas-knap** [comment]
Yes, the original issue is there because the commit https://github.com/UnifiedViews/Plugin-DevEnv/commit/a80d72cfa9af959cda6ea62acd61ded3956ed123 has to be reverted as well

**Comment by AndreAga** [comment]
It works for me. No other problems.

**Comment by jakubklimek** [comment]
Does not work for me though. According to @skodape I would have to redeploy all my instances for my newly compiled DPUs to work.

**Comment by tomas-knap** [comment]
@jakubklimek Test whether it works

**Comment by jakubklimek** [comment]
It does not. Now Core build fails again
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[13,27] error: package eu.unifiedviews.util does not exist
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[15,41] error: cannot find symbol
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[31,4] error: method does not override or implement a method from a supertype
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[53,4] error: method does not override or implement a method from a supertype
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ODCleanStore ....................................... SUCCESS [  2.397 s]
[INFO] dataunit ........................................... SUCCESS [  8.740 s]
[INFO] dataunit-file ...................................... SUCCESS [  0.124 s]
[INFO] dataunit-file-impl ................................. SUCCESS [  4.571 s]
[INFO] dataunit-rdf ....................................... SUCCESS [  4.758 s]
[INFO] dataunit-rdf-impl .................................. SUCCESS [  5.865 s]
[INFO] dataunit-relational-impl ........................... SUCCESS [  6.256 s]
[INFO] commons-app ........................................ FAILURE [  7.536 s]
[INFO] frontend ........................................... SKIPPED
[INFO] backend ............................................ SKIPPED
[INFO] lib ................................................ SKIPPED
[INFO] lib-core ........................................... SKIPPED
[INFO] module-test ........................................ SKIPPED
[INFO] master ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.646 s
[INFO] Finished at: 2015-03-10T15:51:14+01:00
[INFO] Final Memory: 87M/452M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project commons-app: Compilation failure: Compilation failure:
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[13,27] error: package eu.unifiedviews.util does not exist
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[15,41] error: cannot find symbol
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[31,4] error: method does not override or implement a method from a supertype
[ERROR] \Users\Kuba\Documents\GitHub\Core\commons-app\src\main\java\eu\unifiedviews\commons\util\CryptographyImpl.java:[53,4] error: method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :commons-app
```
